return {
  --  {
  --    'yetone/avante.nvim',
  --    event = 'VeryLazy',
  --    lazy = false,
  --    version = false, -- Set this to "*" to always pull the latest release version, or set it to false to update to the latest code changes.
  --    opts = {
  --      claude = {
  --        disable_tools = true,
  --      },
  --    },
  --    -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  --    build = 'make',
  --    -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  --    dependencies = {
  --      'nvim-treesitter/nvim-treesitter',
  --      'stevearc/dressing.nvim',
  --      'nvim-lua/plenary.nvim',
  --      'MunifTanjim/nui.nvim',
  --      --- The below dependencies are optional,
  --      'nvim-telescope/telescope.nvim', -- for file_selector provider telescope
  --    },
  --  },
}
